version: "3.8"

services:
  backend:
    build: ./server
    container_name: backend-app
    ports:
      - "8000:8000"  # Esposto solo per debugging, poi puoi togliere
    environment:
      - DB_HOST=database-provedieti.cb4c6s46olha.us-east-1.rds.amazonaws.com
      - DB_USER=postgres
      - DB_PASSWORD=Eyeswideshut1!
      - DB_NAME=dietiestates25
      - JWT_SECRET=your_jwt_secret
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
