version: "3.8"

services:
  backend:
    build: ./server
    container_name: backend-app
    ports:
      - "8000:8000" 
    env_file:
      - ./.env 
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
