version: "3.8"

services:
  backend:
    build: ./server
    container_name: backend-app
    ports:
      - "8000:8000"  # Esposto solo per debugging, poi puoi togliere
    env_file:
      - ./.env  # se hai un file .env per il backen
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend-app
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
